### ISSUE TITLE
ModuleNotFoundError: No module named 'httplib2'

### ISSUE THREAD

**Issue by charlie-costanzo** [tuanchris/cloud-data-lake#4]
Hi there - I  love this tutorial, it's exactly what I'm hoping to learn. However, I'm running into an issue. 

I'm not sure if this looks familiar - either as a mistake I'm making or as a result of something being out of date - but this error keeps coming up everytime I try to `make run`:

> webserver_1  | ModuleNotFoundError: No module named 'httplib2'

I've done as much research as I can. Everything keeps saying it's related to having two versions of python locally but I don't think that's the issue...

Any insight?

**Comment by tuanchris** [comment]
Hi @charlie-costanzo, this is a very old project, so I guess some of the dependencies broke. I have fixed the issues and ran the pipeline successfully locally. Would you please follow the new instructions in the README file and let me know if the problems are solved? 

![image](https://user-images.githubusercontent.com/52090179/147526796-5d03cefa-8334-4c5b-ad19-6b44f7b6c7cf.png)

**Comment by charlie-costanzo** [comment]
Thank you so much for looking into this @tuanchris, and for the resolution! It appears to be working for me now. Much appreciated!!
